# Generated by Django 5.1.3 on 2024-11-20 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labora13', '0002_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
